### ISSUE TITLE
Bug report: Workflow run failed

### ISSUE THREAD

**Issue by DhruvMitna** [Readme-Workflows/recent-activity#106]
### Checks

- [X] I use a [supported version](https://github.com/Readme-Workflows/recent-activity/blob/main/SUPPORTED_VERSIONS.md) of Recent Activity.
- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing bug reports.

### Description

Whenever the job runs, it fails at `Run Readme-Workflows/recent-activity@v2.3.0`. It says `Error: ENOENT: no such file or directory, open './.github/recent-activity.config.yml'`.
[ The full output](https://pastebin.com/j7YekicT) (https://github.com/DhruvMitna/DhruvMitna/runs/3573634743?check_suite_focus=true)

### Steps to reproduce

1. Fork https://github.com/DhruvMitna/DhruvMitna.
2. Go to the actions tab.
3. Click on Update Readme.
4. Run the job.

### Configuration

```yaml
# update-readme.yml
name: Update README
on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# recent-activity.config.yml
settings:
  commit_msg: "Automatic workflow run update"
  max_lines: 10
  disabled_events:
    - "star"
    - "comments"
  commit_username: "workflow"
  date:
    timezone: "GMT+05:30"
    format: "HH:MM:ss:l d/mm/yyyy o"
  messages:
    added_member: "🤝 Became a collaborator on {REPO}"
    create_repo: "📔 Created {REPO}"
    issue_issue: "❗️ Opened {ID} in {REPO}"
    issue_closed: "✔️ Closed {ID} in {REPO}"
    new_release: "✌️ Released v{ID} for {REPO}"
    pr_merged: "🎉 Merged {ID} in {REPO}"
    create_wiki: "📖 Created wiki {WIKI} in {REPO}"
```

### Expected behaviour

The expected behaviour was to update the readme with the recent activity according to the config.

### Actual behaviour

The actual behaviour is that it updates the readme but it doesnt follow the config and the workflow run fails.

### Failed runs

https://github.com/DhruvMitna/DhruvMitna/runs/3573634743?check_suite_focus=true
