### ISSUE TITLE
Bug report: Failure, dateFormat is not a Function

### ISSUE THREAD

**Issue by OnlyAlec** [Readme-Workflows/recent-activity#114]
### Checks

- [X] I use a [supported version](https://github.com/Readme-Workflows/recent-activity/blob/main/SUPPORTED_VERSIONS.md) of Recent Activity.
- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing bug reports.

### Description

The actions fails, using the `<!--RECENT_ACTIVITY:last_update-->`
I try change the version but heaven don't work, `Unable to resolve action Readme-Workflows/recent-activity@2.3.0, unable to find version 2.3.0`

The error that said the action is:
✖  fatal     TypeError: dateFormat is not a function 

### Steps to reproduce

I follow the Setup Wiki Guide

### Configuration

```yaml
settings:
  username: "OnlyAlec"
  commit_msg: "⚡ Update README with the recent activity"
  max_lines: 5
  readme_file: "./README.md"
  disabled_events:
    - "comments"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT-05:00"
    text: "Ultima Actualizacion: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM TT"
  commit_username: "readme-bot"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
messages:
  comments: "💬 Commented on {ID} in {REPO}"
  issue_opened: "❗️ Opened issue {ID} in {REPO}"
  issue_closed: "✔️ Closed issue {ID} in {REPO}"
  pr_opened: "💪 Opened PR {ID} in {REPO}"
  pr_closed: "❌ Closed PR {ID} in {REPO}"
  pr_merged: "🎉 Merged PR {ID} in {REPO}"
  create_repo: "📔 Created new repository {REPO}"
  fork_repo: "🔱 Forked {FORK} from {REPO}"
  wiki_create: "📖 Created new wiki page {WIKI} in {REPO}"
  added_member: "🤝 Became collaborator on {REPO}"
  changes_approved: "👍 Approved {ID} in {REPO}"
  changes_requested: "🔴 Requested changes in {ID} in {REPO}"
  new_release: "✌️ Released {ID} i
```

### Expected behaviour

That works ? Idk

### Actual behaviour

Don't run the actions, ends with fatal error

### Failed runs

https://github.com/OnlyAlec/OnlyAlec/actions/runs/1278778605
