### ISSUE TITLE
Bug report: events found but "something went wrong"

### ISSUE THREAD

**Issue by matteotumiati** [Readme-Workflows/recent-activity#127]
### Checks

- [X] I use a [supported version](https://github.com/Readme-Workflows/recent-activity/blob/main/SUPPORTED_VERSIONS.md) of Recent Activity.
- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing bug reports.

### Description

I assume the page with supported versions is not updated, but probably I'm missing something.
However I'm using the action like

```yaml
- uses: Readme-Workflows/recent-activity@main
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I'm assuming main targets the latest version available (2.3.1 if I'm not mistaken).

When it runs it is able to find some events but it generates an exception that I cannot understand because it seems to be quite generic as you can see from the screenshot:
 
<img width="1038" alt="Logs from the action" src="https://user-images.githubusercontent.com/3147566/139045055-d49936f0-a6b4-45fe-b70a-e7661fb197a7.png">

### Steps to reproduce

Re-run the action from [here](https://github.com/matteotumiati/matteotumiati/runs/4020671790?check_suite_focus=true)

### Configuration

```yaml
settings:
  commit_msg: "⚡ Update README with the recent activity"
  max_lines: 5
  readme_file: "./README.md"
  disabled_events: [ comments, create_repo, fork ]
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+00:00"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_username: "matteotumiati-bot"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
messages:
  comments: "💬 Commented on {ID} in {REPO}"
  issue_opened: "❗️ Opened issue {ID} in {REPO}"
  issue_closed: "✔️ Closed issue {ID} in {REPO}"
  pr_opened: "💪 Opened PR {ID} in {REPO}"
  pr_closed: "❌ Closed PR {ID} in {REPO}"
  pr_merged: "🎉 Merged PR {ID} in {REPO}"
  create_repo: "📔 Created new repository {REPO}"
  fork_repo: "🔱 Forked {FORK} from {REPO}"
  wiki_create: "📖 Created new wiki page {WIKI} in {REPO}"
  added_member: "🤝 Became collaborator on {REPO}"
  changes_approved: "👍 Approved {ID} in {REPO}"
  changes_requested: "🔴 Requested changes in {ID} in {REPO}"
  new_release: "✌️ Released {ID} in {REPO}"
  new_star: "⭐ Starred {REPO}"
```

### Expected behaviour

If no meaningful events can be found, then I expect to only generate a warning or something, but I don't want the action to fail with an exception.

If events instead are found and aren't matching my `disabled_events`, then I expect the readme.md to be updated accordingly.

### Actual behaviour

A generic exception is created.

```
⬤  debug     Something went wrong
✖  fatal     Error: Invalid status code: 128 
    at ChildProcess.<anonymous> (/home/runner/work/_actions/Readme-Workflows/recent-activity/main/dist/index.js:27214:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
```

### Failed runs

https://github.com/matteotumiati/matteotumiati/actions/runs/1389604748
