### ISSUE TITLE
Bug report: Events found but "something wen wrong" 

### ISSUE THREAD

**Issue by TAKANOME-DEV** [Readme-Workflows/recent-activity#187]
### Checks

- [X] I use a [supported version](https://github.com/Readme-Workflows/recent-activity/blob/main/SUPPORTED_VERSIONS.md) of Recent Activity.
- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing bug reports.

### Description

I know that a similar issue was [opened](https://github.com/Readme-Workflows/recent-activity/issues/127) but mine still fails.
I'm using `Readme-Workflows/recent-activity@v2.3.3`. When the action runs, it find some events but after it throw an Error, take a look at this error:

![update_readme](https://user-images.githubusercontent.com/79809121/169263689-02023219-11f8-4ec7-9e51-c750663c8628.png)

### Steps to reproduce

Re-run the action right [here](https://github.com/TAKANOME-DEV/takanome-dev/runs/6504617750?check_suite_focus=true)

### Configuration

```yaml
# update-readme.yml
name: Update README

on:
  schedule:
    - cron: '*/8 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@v2.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# recent-activity.config.yml
settings:
  commit_msg: '⚡ Update README with the recent activity'
  max_lines: 5
  readme_file: './README.md'
  disabled_events:
    - 'comments'
  url_text: '{REPO}{ID}'
  date:
    timezone: 'GMT+00:00'
    text: 'Last Updated: {DATE}'
    format: 'dddd, mmmm dS, yyyy, h:MM:ss TT'
  commit_name: 'readme-bot'
  # commit_email: '41898282+github-actions[bot]@users.noreply.github.com'
messages:
  comments: '💬 Commented on {ID} in {REPO}'
  issue_opened: '❗️ Opened issue {ID} in {REPO}'
  issue_closed: '✔️ Closed issue {ID} in {REPO}'
  pr_opened: '💪 Opened PR {ID} in {REPO}'
  pr_closed: '❌ Closed PR {ID} in {REPO}'
  pr_merged: '🎉 Merged PR {ID} in {REPO}'
  create_repo: '📔 Created new repository {REPO}'
  fork_repo: '🔱 Forked {FORK} from {REPO}'
  wiki_create: '📖 Created new wiki page {WIKI} in {REPO}'
  added_member: '🤝 Became collaborator on {REPO}'
  changes_approved: '👍 Approved {ID} in {REPO}'
  changes_requested: '🔴 Requested changes in {ID} in {REPO}'
  new_release: '✌️ Released {ID} in {REPO}'
  new_star: '⭐ Starred {REPO}'
```

### Expected behaviour

I expect the readme to be updated after the events are found

### Actual behaviour

An error is thrown `Error: Invalid status code: 128`

### Failed runs

https://github.com/TAKANOME-DEV/takanome-dev/runs/6504617750?check_suite_focus=true
