### ISSUE TITLE
Bug report:  ⬤  debug - Something went wrong 

### ISSUE THREAD

**Issue by jujutsugod** [Readme-Workflows/recent-activity#246]
### Checks

- [X] I use a [supported version](https://github.com/Readme-Workflows/recent-activity/blob/main/SUPPORTED_VERSIONS.md) of Recent Activity.
- [x] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing bug reports.

### Description

Firstly i checked: https://github.com/Readme-Workflows/recent-activity/issues/127,
But it didn't help.

Screenshot:
![image](https://user-images.githubusercontent.com/122545070/212235018-f6744c35-7727-446e-b4ea-ebc135754c5f.png)

### Steps to reproduce

Re-run the action from [here](https://github.com/jujutsugod/jujutsugod/actions/runs/3908260436/jobs/6678248083?check_suite_focus=true)

### Configuration

```yaml
name: Recent Activity

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  activity:
    name: Update activity
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Readme-Workflows/recent-activity@v2.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          CONFIG_FILE: "config.yml"


CONFIG FILE:


settings:
  username: "jujutsugod"
  commit_msg: "Update Recent Activity"
  max_lines: 5
  readme_file: "README.md"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+0:00"
    text: "{DATE}"
    format: "dS mmmm, yyyy @ HH:MMtt Z"
  commit_name: "github-actions"
  commit_email: "actions@github.com"
messages:
  comments: "![comments](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/Comment.svg) Commented on {ID} in {REPO}"
  issue_opened: "![issue_opened](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/IssueOpened.svg) Opened issue {ID} in {REPO}"
  issue_closed: "![issue_closed](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/IssueClosed.svg) Closed issue {ID} in {REPO}"
  pr_opened: "![pr_opened](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/PullRequestOpened.svg) Opened PR {ID} in {REPO}"
  pr_closed: "![pr_closed](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/PullRequestClosed.svg) Closed PR {ID} in {REPO}"
  pr_merged: "![pr_merged](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/PullRequestMerged.svg) Merged PR {ID} in {REPO}"
  create_repo: "![create_repo](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/Repository.svg) Created new repository {REPO}"
  fork_repo: "![fork_repo](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/ForkedRepository.svg) Forked {FORK} from {REPO}"
  wiki_create: "![wiki_create](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/Wiki.svg) Created new wiki page {WIKI} in {REPO}"
  added_member: "![added_member](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/People.svg) Became collaborator on {REPO}"
  changes_approved: "![changes_approved](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/ApprovedChanges.svg) Approved {ID} in {REPO}"
  changes_requested: "![changes_requested](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/RequestedChanges.svg) Requested changes on {ID} in {REPO}"
  new_release: "![new_release](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/Release.svg) Released {ID} in {REPO}"
  new_star: "![new_star](https://cdn.jsdelivr.net/gh/Readme-Workflows/Readme-Icons@main/icons/octicons/StarredRepositoryYellow.svg) Starred {REPO}"****
```

### Expected behaviour

If no meaningful events can be found, then I expect to only generate a warning or something, but I don't want the action to fail with an exception. It however worked on the official repo (i forked it..). but it doesn't work on mine

### Actual behaviour

```bash
⬤  debug     Something went wrong
✖  fatal     Error: Invalid status code: 128 
    at ChildProcess.<anonymous> (/home/runner/work/_actions/Readme-Workflows/recent-activity/main/dist/index.js:27214:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
```

### Failed runs

https://github.com/jujutsugod/jujutsugod/actions/runs/3908260436/jobs/6678248083
