### ISSUE TITLE
Bug report: Error 128 in recent activity

### ISSUE THREAD

**Issue by ahmaddyd** [Readme-Workflows/recent-activity#248]
### Checks

- [X] I use a [supported version](https://github.com/Readme-Workflows/recent-activity/blob/main/SUPPORTED_VERSIONS.md) of Recent Activity.
- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing bug reports.

### Description

![image](https://user-images.githubusercontent.com/81952585/212455516-3ab2172a-ed9f-4609-97da-6ef117584437.png)

### Steps to reproduce

Re-run the action from [here](https://github.com/ahmaddyd/ahmaddyd/actions/runs/3930128253/jobs/6719761134)

### Configuration

```yaml
name: Update RECENT ACTIVITY

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: "./.github/update-readme.config.yml"

settings:
  username: "ahmaddyd"
  commit_msg: "۶Recent Activity Updated🔥٩(̾●•̃̾)۶"
  max_lines: 0
  readme_file: "README.md"
  disabled_events: [event1, event2, event3]
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+07:00"
    text: "<i>Last Update</i> : <b>{DATE}</b>"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_name: "ahmaddyd"
  commit_email: "81952585+ahmaddyd@users.noreply.github.com"
```

### Expected behaviour

It however worked on the official repo. but it doesn't work on mine

### Actual behaviour

```yaml
Run Readme-Workflows/recent-activity@main
  with:
    CONFIG_FILE: ./.github/update-readme.config.yml
    GH_USERNAME: ahmaddyd
  env:
    GITHUB_TOKEN: ***
serializers
{
  IssueCommentEvent: [Function: IssueCommentEvent],
  CommitCommentEvent: [Function: CommitCommentEvent],
  PullRequestReviewCommentEvent: [Function: PullRequestReviewCommentEvent],
  PushEvent: [Function: PushEvent],
  IssuesEvent: [Function: IssuesEvent],
  PullRequestEvent: [Function: PullRequestEvent],
  CreateEvent: [Function: CreateEvent],
  ForkEvent: [Function: ForkEvent],
  GollumEvent: [Function: GollumEvent],
  MemberEvent: [Function: MemberEvent],
  PullRequestReviewEvent: [Function: PullRequestReviewEvent],
  ReleaseEvent: [Function: ReleaseEvent],
  WatchEvent: [Function: WatchEvent]
}
⬤  debug     Getting activity for ahmaddyd
⬤  debug     100 events found for ahmaddyd.
[ '' ]

{ hello: 'readme-workflows.glitch.me' }
⬤  debug     Something went wrong
✖  fatal     Error: Invalid status code: 1[2](https://github.com/ahmaddyd/ahmaddyd/actions/runs/3930128253/jobs/6719761134#step:3:2)8 
    at ChildProcess.<anonymous> (/home/runner/work/_actions/Readme-Workflows/recent-activity/main/dist/index.js:20:171504)
    at ChildProcess.emit (node:events:[3](https://github.com/ahmaddyd/ahmaddyd/actions/runs/3930128253/jobs/6719761134#step:3:3)90:28)
    at maybeClose (node:internal/child_process:106[4](https://github.com/ahmaddyd/ahmaddyd/actions/runs/3930128253/jobs/6719761134#step:3:4):16)
    at Socket.<anonymous> (node:internal/child_process:4[5](https://github.com/ahmaddyd/ahmaddyd/actions/runs/3930128253/jobs/6719761134#step:3:5)0:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:[6](https://github.com/ahmaddyd/ahmaddyd/actions/runs/3930128253/jobs/6719761134#step:3:6)8[7](https://github.com/ahmaddyd/ahmaddyd/actions/runs/3930128253/jobs/6719761134#step:3:8):[12](https://github.com/ahmaddyd/ahmaddyd/actions/runs/3930128253/jobs/6719761134#step:3:13))
```

### Failed runs

https://github.com/ahmaddyd/ahmaddyd/actions/runs/3930128253/jobs/6719761134
