### ISSUE TITLE
Bug report: Build failing

### ISSUE THREAD

**Issue by orhanar** [Readme-Workflows/recent-activity#288]
### Checks

- [X] I use a [supported version](https://github.com/Readme-Workflows/recent-activity/blob/main/SUPPORTED_VERSIONS.md) of Recent Activity.
- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing bug reports.

### Description

Description

It is events-update job that is failing which uses recent activity

https://github.com/orhanar/orhanar/actions/runs/5103398620/jobs/9173612868

Steps to reproduce
https://github.com/orhanar/orhanar/actions/runs/5103398620/jobs/9173612868

Configuration
https://github.com/orhanar/orhanar/commits/master

Expected behaviour
Shouldn't show any errors

Actual behaviour
https://github.com/orhanar/orhanar/actions/runs/5103398620/jobs/9173612868

Failed runs
https://github.com/orhanar/orhanar/actions/runs/5103398620/jobs/9173612868

### Steps to reproduce

Running

https://github.com/orhanar/orhanar/actions/runs/5103398620/jobs/9173612868

### Configuration

```yaml
update-readme.yml

name: Build README

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'
    
jobs:
  readme-update: 
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
     - uses: teoxoy/profile-readme-stats@v2
       with:
        token: ${{ secrets.GH_TOKEN }}
        run: |
         if [[ "$(git status --porcelain)" != "" ]]; then
         git config user.name github-actions[bot]
         git config user.email 41898282+github-actions[bot]@users.noreply.github.com
         git add .
         git commit -m "Update README"
         git push
         fi
  waka-update:
    runs-on: ubuntu-latest
    needs: readme-update
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  events-update:
     runs-on: ubuntu-latest
     needs: waka-update
     steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  blog-update:
    runs-on: ubuntu-latest
    needs: events-update
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://orhanar.github.io/blog/feed.xml" 

recent-activity.config.yml

settings:
  commit_msg: "Automatic workflow run update"
  max_lines: 10
  disabled_events:
    - "star"
    - "comments"
  commit_username: "workflow"
  date:
    timezone: "GMT+05:30"
    format: "HH:MM:ss:l d/mm/yyyy o"
  messages:
    added_member: "🤝 Became a collaborator on {REPO}"
    create_repo: "📔 Created {REPO}"
    issue_issue: "❗️ Opened {ID} in {REPO}"
    issue_closed: "✔️ Closed {ID} in {REPO}"
    new_release: "✌️ Released v{ID} for {REPO}"
    pr_merged: "🎉 Merged {ID} in {REPO}"
    create_wiki: "📖 Created wiki {WIKI} in {REPO}"
```

### Expected behaviour

Run successfully and update the README

### Actual behaviour

Fails

### Failed runs

https://github.com/orhanar/orhanar/actions/runs/5103398620/jobs/9173612868
