### ISSUE TITLE
Bug report: Error Invalid status Code 128

### ISSUE THREAD

**Issue by Robert-W-Ward** [Readme-Workflows/recent-activity#290]
### Checks

- [X] I use a [supported version](https://github.com/Readme-Workflows/recent-activity/blob/main/SUPPORTED_VERSIONS.md) of Recent Activity.
- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing bug reports.

### Description

I have tried to use the action using the sample.yaml but get a fatal error that I have yet to be able to figure out

`{ hello: 'readme-workflows.glitch.me' }
⬤  debug     Something went wrong
✖  fatal     Error: Invalid status code: 128 
    at ChildProcess.<anonymous> (/home/runner/work/_actions/Readme-Workflows/recent-activity/v2.4.1/dist/index.js:20:171504)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)`

### Steps to reproduce

- Follow the set up steps from the wiki
- try to manually trigger action
- fatal error

### Configuration

```yaml
Workflow:
name: Update README

on:
  schedule:
    - cron: '* 1 * * *' # Update every 1 hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Config file in .github/ 
settings:
  #username: "Readme-Workflows" # Replace with your username or comment out this line
  commit_msg: "⚡ Update README with the recent activity"
  max_lines: 5
  readme_file: "./README.md"
  disabled_events:
    - "comments"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+00:00"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_name: "readme-bot"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
  line_prefix: "{NUM}. "
messages:
  comments: "💬 Commented on {ID} in {REPO}"
  push: "⬆️ Pushed {AMOUNT} commit(s) to {REPO}"
  issue_opened: "❗️ Opened issue {ID} in {REPO}"
  issue_closed: "✔️ Closed issue {ID} in {REPO}"
  pr_opened: "💪 Opened PR {ID} in {REPO}"
  pr_closed: "❌ Closed PR {ID} in {REPO}"
  pr_merged: "🎉 Merged PR {ID} in {REPO}"
  create_repo: "📔 Created new repository {REPO}"
  fork_repo: "🔱 Forked {FORK} from {REPO}"
  wiki_create: "📖 Created new wiki page {WIKI} in {REPO}"
  added_member: "🤝 Became collaborator on {REPO}"
  changes_approved: "👍 Approved {ID} in {REPO}"
  changes_requested: "🔴 Requested changes in {ID} in {REPO}"
  new_release: "✌️ Released {ID} in {REPO}"
  new_star: "⭐ Starred {REPO}"
```

### Expected behaviour

Successful update to README.md file 

### Actual behaviour

Fatal error: Invalid status code: 128

### Failed runs

https://github.com/Robert-W-Ward/Robert-W-Ward/actions/runs/5193481684/jobs/9364073688
