### ISSUE TITLE
[HTTP Error]: Status Code 128

### ISSUE THREAD

**Issue by r-rajaneesh** [Readme-Workflows/recent-activity#320]
### Checks

- [X] I use a [supported version](https://github.com/Readme-Workflows/recent-activity/blob/main/SUPPORTED_VERSIONS.md) of Recent Activity.
- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing bug reports.

### Description

```
{ hello: 'readme-workflows.glitch.me' }
⬤  debug     Something went wrong
✖  fatal     Error: Invalid status code: 128 
    at ChildProcess.<anonymous> (/home/runner/work/_actions/Readme-Workflows/recent-activity/v2.4.1/dist/index.js:20:171504)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:3[38](https://github.com/r-rajaneesh/r-rajaneesh/actions/runs/10452994062/job/28942572501#step:3:39):12)
```

### Steps to reproduce

Just a new repo with the old settings.
https://github.com/r-rajaneesh/r-rajaneesh

### Configuration

```yaml
`.github/workflows/update-readme.yml`

name: Update README

on:
  schedule:
    # Runs every first and 2 hrs.
    - cron: '* 2 * * *'
  workflow_dispatch:

jobs:
  activity:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Recent GitHub Activity - Profile Readme
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


`.github/recent-activity.config.yml`
```yml
settings:
  #username: "Readme-Workflows" # Replace with your username or comment out this line
  commit_msg: "Update README with the recent activity"
  readme_file: "./README.md"
  date:
    text: "Last Updated: {DATE} (GMT)"
```
```


### Expected behaviour

Should update the readme.

### Actual behaviour

failed with a HTTP error leading to a non-existent repo on glitch.

### Failed runs

https://github.com/r-rajaneesh/r-rajaneesh/actions/runs/10452994062
