### ISSUE TITLE
Bug report: Invalid status code: 1 at ChildProcess (/recent-activity/v2.4.1/dist/index.js:20:171504)

### ISSUE THREAD

**Issue by fbuireu** [Readme-Workflows/recent-activity#323]
### Checks

- [x] I use a [supported version](https://github.com/Readme-Workflows/recent-activity/blob/main/SUPPORTED_VERSIONS.md) of Recent Activity.
- [x] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing bug reports.

### Description

The action runs properly and fetches the latest GH activity correctly but in the last step it fails. Apparently there's an error in `(/recent-activity/v2.4.1/dist/index.js:20:171504)`

![Image](https://github.com/user-attachments/assets/6a8f2004-c8a2-42f2-ad84-7d8d2501b2fd)

### Steps to reproduce

Just run the action

### Configuration

```yaml
name: GitHub Activity
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    name: Update README files
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        config_file:
          - ./.github/config/github-activity/en.config.yml
          - ./.github/config/github-activity/ca.config.yml
          - ./.github/config/github-activity/it.config.yml
          - ./.github/config/github-activity/es.config.yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Recent Activity 
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: ${{ matrix.config_file }}
      - name: Create and auto-merge PR
        uses: ./.github/actions/create-auto-merge-pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs: update GitHub activity'
          title: '🤖 [AUTOMATED] Update GitHub Activity'
          branch: 'github-activity-update-${{ github.run_number }}'
```

### Expected behaviour

I expect the action to run properly

### Actual behaviour

It fails after fetching and setting al the data correctly

### Failed runs

https://github.com/fbuireu/fbuireu/actions/runs/15940915913
