### ISSUE TITLE
Feature request: Keep the configuration in a file

### ISSUE THREAD

**Issue by PuneetGopinath** [Readme-Workflows/recent-activity#52]
Please check these things before submitting your issue:

- [x] I searched for duplicate or closed feature request [here](https://github.com/PuneetGopinath/github-activity-readme/issues?q=is%3Aissue)

**Is your feature request related to a problem? Please describe.**
N/A.

**Describe the solution you'd like**
I think you should keep the configuration in a separate file (maybe a file like `.github/recent-activity-config.yml`) as there are too many inputs and only add `config_file` as a option in github action inputs which will tell path to the configuration file. I will assign this to my self if you agree with this request and plz help me in the process of doing it.

**Describe alternatives you've considered**
N/A.

**Additional context**
Probaly I will use [js-yaml](https://www.npmjs.com/package/js-yaml) as a dependency to do parse the yaml config.

**Comment by abhijoshi2k** [comment]
Yes. We can have a `recent-activity.config.json` named file.

**Comment by Andre601** [comment]
Agree. Moving the settings to a configuration file seems like a good idea.

I personally have the following file structure in mind:
```yaml
settings:
  username: 'Readme-Workflows'
  commit_message: '⚡ Update README with the recent activity'
  max_lines: 5
  readme_file: './README.md'
  disabled_events: # Maybe we can now have an actual list?
  - 'comment'
  url_text: '{REPO}{ID}'
  date:
    timezone: '0:00' # Would also allow defining timezone names if #49 is worked on
    text: 'Last updated: {DATE}'
    date_format: 'dddd, mmmmm dS, yyyy, h:MM:ss TT'
messages:
  comments: '💬 Commented on {ID} in {REPO}'
  issue_open: '❗️ Opened issue {ID} in {REPO}'
  issue_close: '✔ Closed issue {ID} in {REPO}'
  pr_open: '💪 Opened PR {ID} in {REPO}'
  pr_close: '❌ Closed PR {ID} in {REPO}'
  pr_merge: '🎉 Merged PR {ID} in {REPO}'
  repo_create: '📔 Created new repository {REPO}'
  repo_fork: '🔱 Forked {FORK} from {REPO}'
  repo_watch: '👀 Watching {REPO}'
  wiki_create: '📖 Created new wiki page {WIKI} in {REPO}'
```
