### ISSUE TITLE
Bug report: 

### ISSUE THREAD

**Issue by CatherineOsadciw** [Readme-Workflows/recent-activity#92]
### Checks

- [X] I use a [supported version](https://github.com/Readme-Workflows/recent-activity/blob/main/SUPPORTED_VERSIONS.md) of Recent Activity.
- [X] I [searched the issues page](https://github.com/Readme-Workflows/recent-activity/issues?q=is%3Aissue) for already existing bug reports.

### Description

I just switched to using this fork from the original action, and my activities are not being inserted into my README.  I think this has something to do with the <5 empty items> line in the logs from the action run, pictured below.  

![Screen Shot 2021-08-06 at 12 10 37 AM](https://user-images.githubusercontent.com/26028027/128455134-9f1e9d38-54d9-4b12-94ec-0eb4233c58bf.png)

Is there a time limit on how far back the action is checking for public events/could you provide some guidance on what this line from the logging means? 

Note that the  tag is being added to the README, just no activities (+ the logs seem to indicate a successful write to the README), so I'm wondering if the issue is with some sort of event filtering that isn't immediately obvious.

### Steps to reproduce

1. Run the github-activity workflow (pasted below)
2. Check the logs from the workflow run: events were found and everything was successful, but logs include the line "<5 empty items>"

Example:
![Screen Shot 2021-08-06 at 12 10 37 AM](https://user-images.githubusercontent.com/26028027/128455507-d021b433-74bf-4e51-9b6c-aa5999d8fc2a.png)

3. Check the README raw file and see that the end tag has been inserted, but no activities

![Screen Shot 2021-08-06 at 12 19 52 AM](https://user-images.githubusercontent.com/26028027/128455456-649c4833-6817-4f3e-a4b4-92d0559bdaed.png)

### Configuration

```yaml
# Workflow to update my recent GitHub activity in public repos

name: github-activity
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with my most recent GitHub activity in public repos
    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/recent-activity@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: "workflow_settings.yml"


# Workflow settings
settings:
  username: "CatherineOsadciw"
  readme_file: ./README.md
  commit_msg: 'Updating recent public GitHub activity'
  max_lines: 5
  disabled_events: []
```

### Expected behaviour

Expect to see the last 5 public events, no matter how long ago they were, listed in the README.

### Actual behaviour

Logs + the insertion of the end tag indicate that the README is being written to, but the actual activities are empty.

### Failed runs

https://github.com/CatherineOsadciw/CatherineOsadciw/actions/runs/1103842951
